track: unix
title: UNIX
description: Authentic historical UNIX systems and direct descendants.
systems:
  - unix-v7-pdp11
  - 43bsd-vax
  - amix-a3000
planned:
  - unix-v6-pdp11
  - 211bsd-pdp11
  - system-v
  - xenix
  - sunos4
  - ultrix
  - aux
  - irix
  - osf1
