track: unixish
title: Unixish
description: UNIX-like clones, research systems, descendants and inspired environments.
systems: []
planned:
  - minix
  - coherent
  - lunix-ng-c64
  - plan9
  - inferno
